### PR TITLE
fix a bunch of time related bugs, text size, added new fields for sch…

### PR DESCRIPTION
**Pull request by yighu**
…edule

fix a bunch of time related bugs, text size, added new fields for
schedule  so the event location can be specified in comments if
necessary.

### CODE REVIEW

**Comment by yighu** [comment]
fix issues and made enhancements

**Comment by jkuru** [comment]
I have reviewed the changes.  Please Merge.

**Comment by yighu** [comment]
I didn't find a merge button. Would you able to merge it?

**Comment by jkuru** [comment]
I did merge the fix to Master as of today.  Please pull down the master and certify.

**Pull request merged**
